version: "3.9"  # optional since v3.39.0
services:
  web:
    build: .
    ports:
      - "87000:86000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
